// Generated by CoffeeScript 1.6.3
(function() {
  var allowCrossDomain, app, express, fakedb,
    _this = this;

  express = require('express');

  app = express();

  allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');
    if (req.method === 'OPTIONS') {
      return res.send(200);
    } else {
      return next();
    }
  };

  fakedb = {
    id: 1234,
    name: 'The stream meta-stream',
    slug: 'meta-stream',
    posts: [
      {
        content: 'I want someplace to microblog while I work, so I can record things without going off on tangents, and come back to them later. 9:10PM on Nov 16',
        timestamp: Date.now()
      }, {
        content: 'I also want a record of all of the problems I faced and the decisions I made.',
        timestamp: Date.now()
      }
    ]
  };

  app.configure(function() {
    app.use(allowCrossDomain);
    return app.use(express.bodyParser());
  });

  app.get('/stream/:stream', function(req, res) {
    console.log('got a request for a stream!');
    return res.json(fakedb);
  });

  app.post('/stream/:stream/post', function(req, res) {
    console.log('got a post request to post a post yo');
    console.log(req.body);
    fakedb.posts.unshift(req.body.data);
    return res.end();
  });

  app.listen(80);

}).call(this);
